package br.ufsm.coletaseletivaufsm.containers;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import br.ufsm.coletaseletivaufsm.containers.Containers;

import br.ufsm.coletaseletivaufsm.containers.ContainersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig containersDaoConfig;

    private final ContainersDao containersDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        containersDaoConfig = daoConfigMap.get(ContainersDao.class).clone();
        containersDaoConfig.initIdentityScope(type);

        containersDao = new ContainersDao(containersDaoConfig, this);

        registerDao(Containers.class, containersDao);
    }
    
    public void clear() {
        containersDaoConfig.getIdentityScope().clear();
    }

    public ContainersDao getContainersDao() {
        return containersDao;
    }

}
